# -*- coding: utf-8 -*-
"""First_Colab_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vdeCkrStvMmCIlLvC3i0Fk2OtYzcicq7

#Matrix
"""

import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

mean_value=np.mean(matrix)
mean_value

mode_value=np.argmax(matrix)+1
mode_value

median_value=np.median(matrix)
median_value



"""#List"""

lista=[5,8,11,79,55,55]

max(lista)

min(lista)

sum(lista)

lista[0]

lista.sort()

lista.append(17)
lista

lista.count(55)



